
export const LOCAL_STORAGE_TOKEN_KEY = 'crossmatch.firebase.token';

export const LOGIN_REQUESTED = 'Auth/LOGIN_REQUESTED';
export const LOGIN_SUCCESS = 'Auth/LOGIN_SUCCESS';
export const LOGIN_FAILED = 'Auth/LOGIN_FAILED';
export const SIGNUP_REQUESTED = 'Auth/SIGNUP_REQUESTED';
export const SIGNUP_SUCCESS = 'Auth/SIGNUP_SUCCESS';
export const SIGNUP_FAILED = 'Auth/SIGNUP_FAILED';
export const RESET_PASSWORD_REQUESTED = 'Auth/RESET_PASSWORD_REQUESTED';
export const RESET_PASSWORD_SUCCESS = 'Auth/RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'Auth/RESET_PASSWORD_FAILED';
export const LOGOUT = 'Auth/LOGOUT';
export const CURRENT_EMAIL = 'Auth/CURRENT_EMAIL';
export const CURRENT_PASSWORD = 'Auth/CURRENT_PASSWORD';

export const SET_LOCUM_AGENCIES = 'Auth/SET_LOCUM_AGENCIES';
export const IS_TEMPORARY_PASSWORD = 'Auth/IS_TEMPORARY_PASSWORD';
export const UPDATE_PASSWORD_REQUESTED = 'Auth/UPDATE_PASSWORD_REQUESTED';
export const UPDATE_PASSWORD_SUCCESS = 'Auth/UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'Auth/UPDATE_PASSWORD_FAILED';

export const CALENDAR_NAV_WEEK = 'CALENDAR_NAV_WEEK';
export const CALENDAR_NAV_MONTH = 'CALENDAR_NAV_MONTH';
export const CALENDAR_NAV_YEAR_MONTH = 'CALENDAR_NAV_YEAR_MONTH';
export const CALENDAR_NAV_START_LOADING = 'CALENDAR_NAV_START_LOADING';
export const CALENDAR_NAV_END_LOADING = 'CALENDAR_NAV_END_LOADING';

export const EVENT_LOGOUT = 'logoutEvent';
export const EVENT_SWIPE = 'swipeEvent';
export const EVENT_CONFIRM = 'confirmWeekData';

export const WEEKDATA_SETVALUE_START = "WEEKDATA_SETVALUE_START";
export const FIREBASE_SETVALUE_SUCCESS = "FIREBASE_SETVALUE_SUCCESS";
export const FIREBASE_SETVALUE_FAIL = "FIREBASE_SETVALUE_FAIL";
export const WEEKDATA_LOADED = "WEEKDATA_LOADED";
export const WEEKDATA_CHANGED = "WEEKDATA_CHANGED";
export const WEEKDATA_SAVED = "WEEKDATA_SAVED";
export const SET_VIEWNAME = 'SET_VIEWNAME';

//Booking
export const BOOKING_AGENCY = "medical would like to book you for the following:";
export const BOOKING_UNCONFIRMED_LOCAL_DATA = 'BOOKING_UNCONFIRMED_LOCAL_DATA';
export const BOOKING_UNCONFIRMED_SETVALUE_START = 'BOOKING_UNCONFIRMED_SETVALUE_START';
export const BOOKING_REFUSED_SETVALUE_START = 'BOOKING_REFUSED_SETVALUE_START';
export const BOOKING_ACCEPTED_SETVALUE_START = 'BOOKING_ACCEPTED_SETVALUE_START';
export const BOOKING_UNCONFIRMED_SETVALUE_FINISH = 'BOOKING_UNCONFIRMED_SETVALUE_FINISH';
export const BOOKING_REFUSED_SETVALUE_FINISH = 'BOOKING_REFUSED_SETVALUE_FINISH';
export const BOOKING_ACCEPTED_SETVALUE_FINISH = 'BOOKING_ACCEPTED_SETVALUE_FINISH';
export const AVAILABILITY_SETVALUE_START = 'AVAILABILITY_SETVALUE_START';
export const AVAILABILITY_SETVALUE_FINISH = 'AVAILABILITY_SETVALUE_FINISH';

export const VIEWNAME_WEEK = 'week';
export const VIEWNAME_MONTH = 'month';
export const VIEWNAME_YEAR = 'year';
